---
# AutoClearLagg (ACL) Settings

# Seconds between each clear lagg
seconds: 20

# Things to clear
items: true
mobs: false

# Messages broadcasted
time-left-message: §cClear lagg in {SECONDS} seconds
items-cleared-message: §cCleared {COUNT} items
mobs-cleared-message: §cCleared {COUNT} mobs

# Countdown times
times: [20, 15, 10, 5,]
...
